### ISSUE TITLE
Day 3 Tutorial docs

### ISSUE THREAD

**Issue by Fasian1** [semaphoreP/codeastro#133]
remove `$` from code blocks otherwise copy pastes fail

**Comment by mwhosek** [comment]
Other improvements for next year:

- be clear that answering "y" for code + source repositories will mess up paths, and so my quick-start won't work
- "open" only works for mac :). Find other options to open files that are less platform dependent!
- Similarly: use VS code rather than aquamacs, since that is what folks have been practicing on. This will also help for opening files

---> My shortcuts (using open and aquamacs) caused lots of problems! Be careful to avoid in future!

**Comment by mwhosek** [comment]
Also: remember to mention the afternoon bonus activity (connecting sphinx to ReadTheDocs) during the activity wrap up

**Comment by mwhosek** [comment]
Also: rethink logistics the 3rd part of activity (comparing documentation between groups). This is tricky in-person since all documentation is local at this point (requires switching computers or something)

**Comment by mwhosek** [comment]
To consider: do we want to leave ReadtheDocs as a bonus activity, or do we want to include a session on how to tie sphinx to readthedocs in order to make documentation public? Or, is readthedocs too finicky to try to do a demo for?

**Comment by sblunt** [comment]
Matt, assigning this to you. Feel free to close if addressed!
