### ISSUE TITLE
Filling the diagnostics

### ISSUE THREAD

**Issue by astronom57** [semaphoreP/codeastro#40]
Hi. I came across the workshop announcement on Twitter and eager to participate. 
One question on the diagnostics: 
should I use the editing more to actually type answers in? Or is there any other proper way of doing it? 
Asking because I have not figured out if my edits are visible to me only or saved for all.

Cheers,
Mikhail

**Comment by semaphoreP** [comment]
Hi Mikhail,

Whatever way of doing it that's most comfortable for you should work. Your edits will not be visible to anyone else.  You can also download the notebook and do it on your own machine if that's easier for you. 

Let us know if you have any other questions. Otherwise, feel free to close this issue!
