### ISSUE TITLE
add ssh setup instructions for github authentication

### ISSUE THREAD

**Issue by physical256** [semaphoreP/codeastro#99]
github now has that daft token system so it may be worth adding ssh setup instructions and changing the addresses to git@github.com: ssh type ones for clones in the setup stages

the instructions from free code camp are really well written and could be adapted https://www.freecodecamp.org/news/git-ssh-how-to/

**Comment by semaphoreP** [comment]
Since it's a public repo, I thought folks don't need to authenticate unless they are pushing changes?

**Comment by sblunt** [comment]
Add this to VS Code intro lesson

**Comment by sblunt** [comment]
I incorporated using a personal access token into the VS Code intro (since that's what I use), and linked the ssh instructions David suggested as an alternative. I'm going to send around the VS Code intro video this year, and I'll add it to the installation instructions for future years. Excellent call to have this be part of setup!
